import { headers } from 'next/headers';

/**
 * Get the CSP nonce from the request headers.
 * This should be called in Server Components to access the nonce
 * generated by the middleware and passed via the x-nonce header.
 */
export async function getNonce(): Promise<string> {
  const headersList = await headers();
  return headersList.get('x-nonce') ?? '';
}
