import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Row,
  Section,
  Text,
} from '@react-email/components';

interface AdminNotificationProps {
  type: 'booking' | 'contact';
  fields: Record<string, string>;
  clinicName?: string;
}

const colors = {
  dark: '#241f1b',
  warm: '#f7f4f0',
  accent: '#8d6f58',
  body: '#3a3430',
  border: '#e8e4df',
};

export function AdminNotificationEmail({
  type,
  fields,
  clinicName = 'Silk Beauty Salon',
}: AdminNotificationProps) {
  const title = type === 'booking' ? 'New Booking Request' : 'New Contact Submission';

  return (
    <Html lang="en">
      <Head />
      <Preview>{title} - {clinicName}</Preview>
      <Body style={{ backgroundColor: colors.warm, fontFamily: 'Calibri, Arial, sans-serif' }}>
        <Container style={{ maxWidth: '600px', margin: '0 auto', backgroundColor: '#ffffff', border: `1px solid ${colors.border}` }}>
          <Section style={{ backgroundColor: colors.dark, padding: '32px 40px' }}>
            <Heading style={{ color: '#ffffff', fontSize: '24px', fontWeight: 300, margin: 0 }}>
              {clinicName}
            </Heading>
          </Section>

          <Section style={{ padding: '40px' }}>
            <Heading style={{ color: colors.dark, fontSize: '20px', fontWeight: 400, marginBottom: '24px' }}>
              {title}
            </Heading>
            <Section style={{ backgroundColor: colors.warm, padding: '24px', borderRadius: '4px' }}>
              {Object.entries(fields).map(([label, value]) => (
                <Row key={label}>
                  <Column style={{ width: '150px', color: colors.accent, fontWeight: 'bold', padding: '8px 0' }}>
                    {label}
                  </Column>
                  <Column style={{ color: colors.dark, padding: '8px 0', wordBreak: 'break-word' }}>
                    {value}
                  </Column>
                </Row>
              ))}
            </Section>
            <Text style={{ color: colors.body, fontSize: '14px', lineHeight: '20px', marginTop: '24px' }}>
              This notification was generated by the website email service.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}
